config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'
  get 'sessions/new'
  delete '/logout', to: 'sessions#destroy'
  post   '/login',  to: 'sessions#create'
  resources :users, only: %i[create]
  resources :rooms
  resources :rounds, only: %i[create]
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :host, class_name: 'User'
  belongs_to :game_type
  has_many :users
  has_many :rounds

  validates :name, presence: true, uniqueness: true

  def playing?
    rounds.any?(&:playing?)
  end

  def voting?
    rounds.any?(&:voting?)
  end

  def state
    playing? ? '進行中' : '待機中'
  end

  def current_round
    rounds.order(id: :desc)&.first
  end

  def all_users_has_voted?
    users.any?(&:not_finished_voting?) ? false : true
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :create_room, only: [:index]
  before_action :create_user, only: [:index]

  # GET /rooms
  def index; end

  # GET /rooms/1
  def show
    redirect_to :root, flash: { error: 'please log in' } and return unless logged_in?

    redirect_to :root, flash: { error: 'ゲーム進行中の部屋には入れません。' } and return if @room.playing? || @room.voting?
  end

  def create_room
    @room = Room.new
  end

  def create_user
    @user = User.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    redirect_to :root, flash: { error: 'please log in' } and return unless logged_in?

    @room = Room.new(room_params.merge(host: current_user))
    if @room.save
      flash[:success] = 'Room was successfully created'
      redirect_to room_path(@room, password: @room.password)
    else
      flash.now[:error] = @room.errors_html
      render :index
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  def destroy
    redirect_to :root, flash: { error: 'please log in' } and return unless logged_in?

    @room = Room.find_by(id: params[:id], host: current_user)
    redirect_to :root, flash: { error: '部屋が存在しません。' } and return unless @room

    redirect_to :root, flash: { error: 'ユーザが入室しています。' } and return if @room.users.count.positive?

    @room.destroy
    redirect_to :root, flash: { success: "部屋「#{@room.name}」を削除しました。" }
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      params[:password] ||= ''
      @room = Room.find_by(id: params[:id], password: params[:password])
      unless @room
        flash[:error] = '部屋IDかパスワードが間違っています。'
        redirect_to :root
      end
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :password, :game_type_id)
    end
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <div class="field">
    <%= form.text_field :name, placeholder: :Name %>
  </div>

  <div class="field">
    <%= form.password_field :password, placeholder: :Password %>
  </div>

  <div class="field">
    <%= form.collection_select :game_type_id, GameType.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_host_item.html.erb
<div class="sidebar-item">
  議論時間：<%= select_tag(:minutes, options_for_select(1..10, 5), id: 'minutes')%>分
</div>
<%= button_tag('START', type: 'button', id: 'start', class: 'sidebar-item') %>
<%= button_tag('RESET', type: 'button', id: 'reset', class: 'sidebar-item') %>

app/views/rooms/_howto_play_ww.html.erb
<h2>ワードウルフの遊び方</h2>
<ol>
  <li>全員が入室するまで待ちます</li>
  <li>ホストが議論時間を設定します</li>
  <li>ホストが START を押します</li>
  <li>各自にお題のワードが表示されます</li>
  <li>時間切れになるまで、会話をしてウルフ（少数派）を探ります</li>
  <li>時間切れになったらウルフだと思うユーザに投票します </li>
  <li>最後のユーザが投票したら結果が発表されます</li>
</ol>

app/views/rooms/_howto_play_yw.html.erb
<h2>Yes/No ウルフの遊び方</h2>
<ol>
  <li>全員が入室するまで待ちます</li>
  <li>ホストが議論時間を設定します</li>
  <li>ホストが START を押します</li>
  <li>各自に役職とワードが表示されます
    <ul>
      <li>村人: ワードはわかりません。司会に質問して答えを探りましょう</li>
      <li>ウルフ: ワードがわかります。ばれないように司会に質問して全体を答えに導きましょう</li>
      <li>司会: ワードがわかります。みんなの質問に yes/no/わからない で答えましょう</li>
    </ul>
  </li>
  <li>答えがわからず時間切れになったら全員が負けです</li>
  <li>時間切れになる前に答えがわかったらホストが答えが当たったボタンを押します</li>
  <li>誰がウルフだったか話し合って、怪しい人に投票しましょう</li>
  <li>最後のユーザが投票したら結果が発表されます</li>
</ol>

app/views/rooms/_list.html.erb
<table class="room-list">
  <thead class="room-list-header">
    <tr class="room-list-row">
      <th class="room-list-cell">Name</th>
      <th class="room-list-cell">Host</th>
      <th class="room-list-cell">State</th>
      <th class="room-list-cell" colspan="2"><i class="fab fa-wolf-pack-battalion"></i></th>
    </tr>
  </thead>

  <tbody>
    <%# TODO: allだとすべて出てくるので、ここでuserがいるroomに絞るか、userが全員退出したらroomを削除したい %>
    <% Room.all.each do |room| %>
      <tr class="room-list-row">
        <td class="room-list-cell">
          <%= room.name %>
          <%= link_to('<i class="fas fa-trash-alt"></i>'.html_safe, room_path(room), method: :delete, data: { confirm: "部屋「#{room.name}」を削除しますがよろしいですか？" }, class: 'destroy-room') if current_user&.host?(room) %>
        </td>
        <td class="room-list-cell"><%= room.host&.name %></td>
        <td class="room-list-cell"><%= room.state %></td>
        <%= form_with(model: room, method: :get, local: true) do |form| %>
          <td class="room-list-cell">
            <%= room.password.present? ? password_field_tag(:password, nil, id: "room_password_#{room.id}", placeholder: :Password) : :Passなし %>
          </td>
          <td><%= form.submit('参加', class: :button) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/_result.html.erb
<h2>結果</h2>
<div class="result-container">
  <% if round.winner&.wolf? %>
    <h3>ウルフの勝ち！</h3>
    <%= image_tag("character_hitsuji_ookami.png", alt: "wolf wear a sheep skin", class: "result-image") %>
  <% elsif round.winner&.human? %>
    <h3>村人の勝ち！</h3>
    <%= image_tag("villagers.png", alt: "villagers", class: "result-image" ) %>
  <% else %>
    <h3>ワードを当てられなかったので全員負け！</h3>
  <% end %>
  <table class="result-table">
    <tr><th>ユーザ</th><th>役職</th><th>ワード</th><th>投票先</th></tr>
    <% Round.result(round).each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.role_name %></td>
        <td><%= user.word_name %></td>
        <td><%= user.vote_to %></td>
      </tr>
    <% end %>
  <table>
<div>

app/views/rooms/_theme.html.erb
<% role, word = round.role_and_word(current_user) %>
<h2>お題</h2>
<dl>
  <dt class="theme-title">your word</dt>
  <dd class="theme-body"><%= word&.name || '？' %></dd>
  <% if round.room.game_type.yes_no_wolf? %>
    <dt class="theme-title">your role</dt>
    <dd class="theme-body"><%= role.name %></dd>
  <% end %>
</dl>
<%= button_tag('答えがあたった！', type: 'button', id: 'correct') if current_user.host? && round.room.game_type.yes_no_wolf? %>

app/views/rooms/_users.html.erb
<h2>参加者</h2>
<table>
  <tbody>
    <% current_user.room&.users&.each do |user| %>
      <tr class="attendees-row">
        <% if current_user.host? %>
          <td class="attendees-cell"><%= button_tag('<i class="fas fa-skull-crossbones"></i>'.html_safe, data: { user_id: user.id }, type: 'button', class: 'kick') if user != current_user %></td>
        <% end %>
        <td class="attendees-cell"><%= user.name %><%= '(Host)' if user.host? %></td>
        <td class="attendees-cell">
          <% if user != current_user %>
            <%= button_tag('投票', data: { user_id: user.id }, class: 'vote', disabled: !current_user.room.current_round&.voting? || current_user.has_voted? || user.facilitator?) %>
          <% end %>
        </td>
        <td class="attendees-cell">
          <span class="voted">
            <%= "<i class='fas fa-vote-yea'></i>".html_safe if current_user.room.current_round&.voting? && user.has_voted? %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<header class="header">
  <p class="site-title-sub">Know today, Power tomorrow</p>
  <h1 class="site-title"><i class="fab fa-wolf-pack-battalion"></i>WORD-WOLF<i class="fab fa-wolf-pack-battalion"></i></h1>
  <p class="site-description">ワードウルフのゲームマスターツールです
    <br>オンラインで遊ぼう</p>
</header>

<section class="about">
  <div class="op-area">
    <h2 class="heading">このサイトの遊び方</h2>
    <div class="about-text">
      <h3>1. アカウントを作ってね</h3>
      <ul>
        <li>名前はユニークです。早いもの勝ちです。</li>
        <li>アカウントを作ると自動的にログインします。</li>
      </ul>
      <h3>2. ゲーム部屋を作ってね</h3>
      <ul>
        <li>入室パスワードはなくても大丈夫です。</li>
        <li>ゲームの種類を選んでください。ワードウルフとYesNoウルフが選べます。</li>
        <li>部屋名もユニークです。早いもの勝ちです。</li>
      </ul>
      <h3>ゲームの種類</h3>
      <h4>ワードウルフ</h4>
      <p>みんなでお題について話し合う中、みんなとは異なるお題を与えられた少数派の人（ワードウルフ）を探し出すゲームです。</p>
      <h4>YesNoウルフ</h4>
      <p>司会に対してみんなで質問を繰り返しながら、制限時間内に答えにたどり着くゲームです。 1人だけ答えを知っているウルフは、自分がウルフだとバレてはいけません。</p>
    </div>
  </div>
</section>

<section id="account" class="account">
  <h2 class="heading">アカウント</h2>
  <div class="account-container">
    <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: :delete, class: :button %>
    <% else %>
      <div class="account-form">
        <div class="account-inner-form">
          <h3 class="">アカウント登録</h3>
          <%= render 'users/form', user: @user %>
        </div>
        <div class="account-inner-form">
          <h3 class="">ログイン</h3>
          <%= render 'sessions/form' %>
        </div>
      </div>
    <% end %>
  </div>
</section>
<section class="room">
  <h2 class="heading">部屋を作る</h2>
  <div class="room-form">
    <%= render 'form', room: @room %>
  </div>
</section>


<section class="rooms">
  <h2 class="heading">お部屋</h2>
  <div class="rooms-container">
    <%= render 'list' %>
  </div>
</section>

app/views/rooms/show.html.erb
<h1 id="room" class="room-title" data-id="<%= @room.id %>" data-game-type-name="<%= @room.game_type.name %>">
  部屋:<%= @room.name %><span style="font-size: 2rem">(<%= @room.game_type.name %>)</span>
</h1>

<div class="room-container">
  <%# 参加者 %>
  <div class="sidebar-box">
    <div id="users" class="attendees-area">
      <%= render 'users' %>
    </div>

    <div class="leave-area">
      <%= button_to('退室', root_path, method: :get, id: 'leave', class: 'sidebar-item') %>
    </div>

    <%# ホスト管理項目 %>
    <div id="host_item">
      <%= render 'host_item' if current_user.host?(@room) %>
    </div>
    <div class="howto-play">
      <%= render @room.game_type.word_wolf? ? 'howto_play_ww' : 'howto_play_yw' %>
    </div>
  </div>

  <%# お題 %>
  <div class="main-box">
    <div id="theme"></div>

    <%# けっかはっぴょうーーー！！ %>
    <div id="result"></div>
  </div>
</div>

<%# TODO: 取り急ぎ！ %>
<style>
select,button,input {
  color: black;
}
</style>